include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**, lib/models/*.g.dart, lib/models/*.freezed.dart, lib/**/*.g.dart, lib/**/*.freezed.dart]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions
    - prefer_single_quotes
    - close_sinks
    - always_declare_return_types
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_final_in_for_each
    - prefer_relative_imports